a = int(input("Enter a number: "))
b = int(input("Enter another number: "))
print("addition: =", a+b)
print("subtraction: =", a-b)
print("multiplication: =", a*b)
print("division: =", a/b)
print("modules: =",a%b)